### ISSUE TITLE
emacsclient as editor giving error

### ISSUE THREAD

**Issue by muralikodali** [Linus-Mussmaecher/rucola#1]
in configuration file,  i have configured the editor as below:

```
editor = ["emacsclient --tty", "%p"]
```

running emacsclient as editor is producing the following error.

```
Error: IO(Os { code: 2, kind: NotFound, message: "No such file or directory" })

```

**Comment by Linus-Mussmaecher** [comment]
Internally, [Command](https://doc.rust-lang.org/std/process/struct.Command.html) is used to process your editor command. As far as I can see, Command requires you to split your actual command and your arguments, so in your case
```
 editor = ["emacsclient", "--tty", "%p"]
```
should probably work.
In my testing , `["helix -v", "%p"]` produced exactly the same error while `["helix", "-v", "%p"]` worked.

Command also doesn't process your shell aliases, so if `emacsclient` is an alias set at shell level, this might also be the source of your error.

**Comment by muralikodali** [comment]
thanks for your suggestion.
emacsclient is now working as intended.
