### ISSUE TITLE
provide install via Homebrew

### ISSUE THREAD

**Issue by zachvalenta** [Linus-Mussmaecher/rucola#10]
Project looks great, just thinking it would be nice to have install available via macOS package manager as well.

**Comment by Linus-Mussmaecher** [comment]
Hi,

I'm not a Mac or Homebrew user myself, but I have configured a tap and you should be able to install the program via
```
brew install Linus-Mussmaecher/tap/rucola
```
Does this not work as I expect it to? In that case, any errors or other help are much appreciated.

**Comment by zachvalenta** [comment]
It works! Many thanks. Now, to dig into the tool and figure out how it works :)

**Comment by Linus-Mussmaecher** [comment]
That's great to hear!

Feel free to contact me if you have any questions.
