### ISSUE TITLE
Wrong command for exemplary custom editor

### ISSUE THREAD

**Issue by lukeflo** [Linus-Mussmaecher/rucola#12]
**Describe the bug**
When uncommenting the [example line](https://github.com/Linus-Mussmaecher/rucola/blob/c41e8eac04dc2521d07fcc80fc7838fab1064b95/default-config/config.toml#L31) of the default config file, opening a file will lead to a crash

**To Reproduce**
Uncomment the named line and try to open a file with `e`.

**Expected behavior**
Should open Helix.

**Desktop (please complete the following information):**
 - OS: Void Linux
 - Used editor: Helix

**Additional context**
You simply added the wrong command name. To open Helix you have to use the command **`hx`** not `helix`. Thus, changing the line to `# editor=["hx", "%p"]` makes it work!

Issue #11 might be related!

**Comment by Linus-Mussmaecher** [comment]
Hi,

this seems to be not necessarily correct. On my system , helix installed with the executable name `helix` and I needed to add `hx` as an alias manually. I am not sure what this depends on, but I could add a note to the wiki example if that helps.

**Comment by lukeflo** [comment]
Ah OK. You might be running Mac? On Linux its definitely `hx`.

**Comment by Linus-Mussmaecher** [comment]
No, I'm running Arch Linux and installed it from the AUR with `yay` which wraps `pacman`. I was confused myself why this happened, as most online sources talk about `hx` (which is why I immediately added that as an alias).

**Comment by lukeflo** [comment]
Weird. But an extra hint as you mentioned should be enough 😉
