### ISSUE TITLE
Broken view syntax for browsers on Windows

### ISSUE THREAD

**Issue by graphixillusion** [Linus-Mussmaecher/rucola#3]
The default config.toml has this config about the viewer:
```
viewer = [
    "firefox",
    "%p",
]
```
The problem with this config is that it doesn't do the job becouse firefox, like any other browser (atleast on Windows OS) wants this syntax:
```
file:///%p
```
So if the path is `C:\Temp\test.md` the right argument to pass to the browser is 
`file:///C:\Temp\test.md` or `file:///C:/Temp/test.md`
(works both ways)

How to achieve this?

**Comment by Linus-Mussmaecher** [comment]
On Unix systems, the command line arguments on firefox work in such a way that calling
```
 firefox /home/linus/MyNotes/TestNote.md
```
will open firefox on the file URL `file:///home/linus/MyNotes/TestNote.md`. I'm very surprised that this does not work on Windows as well.
I will do some testing on a Windows machine and then report back.

My current suggested solution would be something like changing the creation of the command as follows:
 - **Current behaviour**: If any of the arguments in the config are exactly "%p", replace by the file path.
 - **Planned behaviour**: If any of the arguments in the config _contain_ "%p", replace that appearance by the file path.

Then you could achieve your behaviour with the config `viewer = ["firefox", "file:///%p"]` as your suggested.

**Comment by graphixillusion** [comment]
Well actually if i run this in a command prompt it works:

firefox c:\temp\test.md

**Comment by graphixillusion** [comment]
Ok for this i think i have found the source of the problem: it doesn't work becouse the path passed is

c:\Temp\.html/test.html

Windows doesn't accept this kind of path: it must have all \ or all / not mixed. So these works 

1. c:\Temp\.html\test.html
2. c:/Temp/.html/test.html

And this doesn't:

c:\Temp\.html/test.html

**Comment by Linus-Mussmaecher** [comment]
In this case, what is your specified vault path in your config file?
If it's something like `C:\Temp` can you try to instead put `vault_path = `C:/Temp`? Currently, the path to the HTMLs is found by prepending your vault path to `/.html/<note-name>.html`, so this might fix the issue.

If you are simply running rucola in your note folder without a configured `vault_path`, then this is probably an issue with `std::env::current_dir()` returning a path with `\`.
I will try to update the next version in a way that stadardizes use of `\` and `/` across the program, but maybe the above helps for now?

**Comment by graphixillusion** [comment]
I didn't specify any vault_path in the config. I've tried with the config you suggested but still the same result.

**Comment by Linus-Mussmaecher** [comment]
In this case, there must be some internal issue with the way rucola currently reads and build the paths.
I will have to do my own tests, and I'll inform you of any results once I have any.

**Comment by Linus-Mussmaecher** [comment]
This issue has been fixed by canonicalizing all paths before sending them to external applications (and thus converting to full `\` on Windows and full `/` on Unix systems).

The next release, `0.3.4` coming probably tomorrow along with some other bug fixes, will contain this fix. No further action should be necessary.
