### ISSUE TITLE
Installation with `cargo install rucola-notes` does not create `~/.config/rucola` file or folder

### ISSUE THREAD

**Issue by StevenBlack** [Linus-Mussmaecher/rucola#6]
Hi!  Nice project!  👍🏻 

**Describe the bug**
Installation with `cargo install rucola-notes` does not create `~/.config/rucola` file or folder.

**To Reproduce**

1. On a bare machine with Rust 1.80 installed, do `cargo install rucola-notes` as per docs.  I'm on rucola-notes v0.3.6.

**Expected behavior**
A file named `~/.config/rucola` or a folder named `~/.config/rucola/` with assets therein should be created. Docs are unclear whether it should be a file or folder.  Since CSS is mentioned, I'm guessing it should be a folder but it's unclear.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS latest, Rustlang latest

**Additional context**
* Help via `rucola -h` is not helpful in this case.
* I would suppose `rucola --init` or something to be described in help in case rucola is unable to create its own operating environment.
* Docs should contain the default contents of `~/.config/rucola` file or folder so people can confidently get started with personal config.

**Comment by StevenBlack** [comment]
Just noticed the `[rucola](https://github.com/Linus-Mussmaecher/rucola/tree/main)/[default-config](https://github.com/Linus-Mussmaecher/rucola/tree/main/default-config) folder.

That should be mentioned in the main readme.

**Comment by Linus-Mussmaecher** [comment]
> Hi! Nice project! 👍🏻

I'm glad your like it!

> **Describe the bug** Installation with `cargo install rucola-notes` does not create `~/.config/rucola` file or folder.

I'm no Mac user, but if I read the documentations of the `directories` crate correctly the default configuration location should be `/Users/<User>/Library/Application Support/rs.rucola` on MacOS.
Does that folder get created (and contain the files) as expected?

> **Expected behavior** A file named `~/.config/rucola` or a folder named `~/.config/rucola/` with assets therein should be created. Docs are unclear whether it should be a file or folder. Since CSS is mentioned, I'm guessing it should be a folder but it's unclear.

I have made the Wiki clearer in that section, also including the expected location for all OSs, not just Linux. It should be folder, with five files (as in `default_config`) in it.
I have also included more information related to the configuration files in the main README.
 
>     * I would suppose `rucola --init` or something to be described in help in case rucola is unable to create its own operating environment.

In theory, rucola should also create a (more limited) default config, style and CSS in case it cannot find any and still work out of the box. Are there any errors when you start rucola?
Are the created HTML just plain or do they link to a CSS?


Thanks for your help!

**Comment by StevenBlack** [comment]
Ah thanks for the reply.

Just checking... **YES** the config folder is created (in my case) at

```
~/Library/Application Support/rs.rucola
```
So that worked — my mistake.  It's interesting, however, that the actual folder name ends up as `rs.rucola` on MacOS.

It's also notable that on MacOS the `~/.config/` folder is also commonly used for app config.

> Are there any errors when you start rucola?

No, rucola starts up fine.  I am having difficulty launching with `$EDITOR` but I'll see if that persists now that I know where config lives 😄

**Comment by Linus-Mussmaecher** [comment]
Ah, that's great to hear.
The config location/name is managed by the `confy`/`directories` crate, so at least it will be  consistent among other rust crates using those.

Let me know if you have any further issues or questions!
