### ISSUE TITLE
Support markdown style links

### ISSUE THREAD

**Issue by petrisch** [Linus-Mussmaecher/rucola#8]
If I'm not mystaken, links in the style `[text](link)` are not supported,
and probably aren't because of Comrak right?

So if thats the case, you can close this, cause its the wrong place...

btw great tool! Love it!

**Comment by Linus-Mussmaecher** [comment]
Thanks for your feedback, I'm great you like it!

Links in this style are currently supported for external links only, e.g. `[Markdown](https://en.wikipedia.org/wiki/Markdown)` works and creates a weblink in the finished HTML file. This is supported in Comrak by default. They are currently not supported for internal links, i.e. you can't use `[other](OtherNote)` to link to `OtherNote.md`.

Note that `[[Other Note|other]]` (named wiki links) _does_ work and achieves exactly the result your are probably looking for. However, if you already have a collection of notes with `[...](...)` links, you probably don't want to convert. (Side note: I guess `grep` or `ripgrep` could convert them automatically in a heartbeat, but again, probably not what you want / are used to.)

About my current process: `[[...|...]]]` and `[[...]]` wikilinks are recognized by comrak, but they are not converted to working links automatically. Instead I parse the markdown note to get a syntax tree (with comrak), then search that tree for wiki links and point them to the right HTML file manually. This modified syntax tree is then converted into HTML (again by comrak).

So I suppose I could also search the syntax tree for 'normal' links (`[...](...)`), check if it's an external or an internal link and store that information in the tree as well. It's possible, I think - I'll keep it in mind for the next release.

**Comment by petrisch** [comment]
Ah I see why that makes a differents.

If Cormak is providing that info in the AST, that should be the best approach.
If not, maybe also just let it fail, when searching for the backlink, could be a solution?

The reason for [...](...) is, that I create the HTML using Sphinx with the Myst parser, and that one doesn't support it.
Maybe I should change that one day, or as you suggest convert them beforehand.

**Comment by Linus-Mussmaecher** [comment]
This has been implemented with the latest release 0.4.0.
